### ISSUE TITLE
Error while running test file

### ISSUE THREAD

**Issue by SelfShubham** [Microbial-Ecology-Group/AMRplusplus#41]
While running following command 
nextflow run main_AMR++.nf -profile conda

 N E X T F L O W   ~  version 24.04.3

Launching `main_AMR++.nf` [elegant_gauss] DSL2 - revision: f6bfe39b99

 A M R + +    N F   P I P E L I N E
 ===================================
 reads being analyzed : /home/ncim/AMRplusplus-3.0.6/data/raw/*_R{1,2}.fastq.gz
 output folder        : test_results
 
    AMR++ Nextflow Pipeline Help
    =============================

    Available pipelines:
        - demo: Run a demonstration of AMR++
        - standard_AMR: Run the standard AMR++ pipeline
        - fast_AMR: Run the fast AMR++ pipeline without host removal.
        - standard_AMR_wKraken: Run the standard AMR++ pipeline with Kraken
    Available pipeline subworkflows:
        - eval_qc: Run FastQC analysis
        - trim_qc: Run trimming and quality control
        - rm_host: Remove host reads
        - resistome: Perform resistome analysis
        - align: Perform alignment to MEGARes database
        - kraken: Perform Kraken analysis
        - qiime2: Perform QIIME 2 analysis
        - bam_resistome: Perform resistome analysis on BAM files

    To run a specific pipeline/subworkflow, use the "--pipeline" option followed by the pipeline name:
        nextflow run main_AMR++.nf --pipeline <pipeline_name> [other_options]

    To analyze your samples or otherwise change how AMR++ runs, modify the "params.config" file 
    or add more parameters to the command line.

    Finally, consider your computing environment and modify the "-profile" option. By default,
    AMR++ assumes all software dependencies are in your $PATH, as in the "local" profile. Here are 
    the other options:
        - local: Assumes all sofware is already in your $PATH
        - local_slurm: Local installation and adds control over slurm job submission.
        - conda: Uses "mamba" to install a conda environment. 
        - conda_slurm: Uses "mamba" and adds control over slurm job submission.
        - singularity: Uses a "singularity" image container.
        - singularity_slurm: Singularity image and adds control over slurm job submission.
        - docker: Uses a docker image container.

    To include SNP analysis, add `--snp Y` to your command.
    
    To include deduplicated count analysis, add `--deduped Y` to your command. 
    Please be aware that adding deduplicated counts will significantly increase run time and temp file storage requirements.

    
===================================
Running a demonstration of AMR++
===================================
        
[-        ] process > FAST_AMRplusplus:FASTQ_QC_WF:fastqc                    -
[-        ] process > FAST_AMRplusplus:FASTQ_QC_WF:multiqc                   -
[-        ] process > FAST_AMRplusplus:FASTQ_TRIM_WF:runqc                   -
[-        ] process > FAST_AMRplusplus:FASTQ_TRIM_WF:QCstats                 -
[-        ] process > FAST_AMRplusplus:FASTQ_RESISTOME_WF:build_dependencies -
[-        ] process > FAST_AMRplusplus:FASTQ_QC_WF:fastqc                    -
[-        ] process > FAST_AMRplusplus:FASTQ_QC_WF:multiqc                   -
[-        ] process > FAST_AMRplusplus:FASTQ_TRIM_WF:runqc                   -
[-        ] process > FAST_AMRplusplus:FASTQ_TRIM_WF:QCstats                 -
[-        ] process > FAST_AMRplusplus:FASTQ_RESISTOME_WF:build_dependencies -
[-        ] process > FAST_AMRplusplus:FASTQ_RESISTOME_WF:bwa_align          -
[-        ] process > FAST_AMRplusplus:FASTQ_RESISTOME_WF:runresistome       -
[-        ] process > FAST_AMRplusplus:FASTQ_RESISTOME_WF:resistomeresults   -
[-        ] process > FAST_AMRplusplus:FASTQ_RESISTOME_WF:runrarefaction     -
[-        ] process > FAST_AMRplusplus:FASTQ_RESISTOME_WF:plotrarefaction    -
Creating env using mamba: /home/ncim/AMRplusplus-3.0.6/envs/AMR++_env.yaml [cache /home/ncim/AMRplusplus-3.0.6/envs/AMR++_env-f6a872478a3709bc95dfc426aba819e3]

ERROR ~ Error executing process > 'FAST_AMRplusplus:FASTQ_QC_WF:fastqc (3)'

Caused by:
  Failed to create Conda environment
    command: mamba env create --prefix /home/ncim/AMRplusplus-3.0.6/envs/AMR++_env-f6a872478a3709bc95dfc426aba819e3 --file /home/ncim/AMRplusplus-3.0.6/envs/AMR++_env.yaml
    status : 1
    message:
      Traceback (most recent call last):
        File "/home/ncim/anaconda3/bin/mamba", line 7, in <module>
          from mamba.mamba import main
        File "/home/ncim/anaconda3/lib/python3.6/site-packages/mamba/mamba.py", line 53, in <module>
          import mamba.mamba_api as api
      ImportError: /home/ncim/anaconda3/lib/python3.6/site-packages/mamba/mamba_api.cpython-36m-x86_64-linux-gnu.so: undefined symbol: archive_write_add_filter_zstd
 -- Check '.nextflow.log' file for details

Please help me to solve this error.

**Comment by susheelbhanu** [comment]
Your conda environment is missing 'mamba'. After you activate the `AMR++_env`, run the following:
`conda install conda-forge::mamba`. 

I had the same issue and this solved it.

**Comment by EnriqueDoster** [comment]
Thank you, yes this should be solution.

Otherwise, I recommend making the conda environment first, activating it and then you can run AMR++ using the `-profile local` instead. Let us know if you run into further issues!
